### ISSUE TITLE
An issue in Bank.sol

### ISSUE THREAD

**Issue by 0xbeny** [PatrickAlphaC/denver-security-challenges#1]
```
function withdraw(address to, uint256 amount) public {
        balances[msg.sender] -= amount;
        IERC20(erc20).transferFrom(address(this), to, amount);
 }
```
`to` parameter can be anyone that is not the owner of the deposited funds

To fix the issue follow the below the steps
Add a check at the beginning:
`require( amount>0 && amount<=balances[msg.sender]);`

use
` IERC20(erc20).transferFrom(address(this), msg.sender, amount);`
instead of
` IERC20(erc20).transferFrom(address(this), to, amount);`

**Comment by PatrickAlphaC** [comment]
:D Nice work! 

Closing for now... Perhaps we should add the answer key in the readme?

**Comment by 0xbeny** [comment]
Sure, I'll add it asap
