### ISSUE TITLE
An issue in Truster.sol

### ISSUE THREAD

**Issue by 0xbeny** [PatrickAlphaC/denver-security-challenges#2]
`flashloan` method does not check the given inputs:
`amount` can be `0`
`borrower` and `target` can be any address

`balanceBefore` holds the balance of the contract before function call and there is an if statement that checks balance of contract after `functionCall`. so, we cannot steal the balance in `functionCall`.

The attacker does not have any amount of the `token`.
There is a method in `ERC20` that is called approve.

To steal all of the balance of the Truster contract, we do the following steps:

1. pass `0` as `amount`( the method does not check the amount that it  should not be zero)
2. pass the attacker contract as `borrower`
3. pass the address of `token` as `target`
4. construct `data`  with `abi.encodeWithSignature("approve(address,uint256)", attacker, <all the balance of the Truster>);`
5. the transaction will execute successfully because we borrow 0 of the `token`
6. after all these are done. regarding what `approve ` does, we have the permission to steal all the balance of the `Truster` with a simple `transferFrom(<Truster address>,<Attacker address>,<all the balance>)  `

**Comment by PatrickAlphaC** [comment]
😈
Perhaps we should add an answer key?
